// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_crazed_criminal = "CgkIpt2t-9MXEAIQBw"; // <GPGSID>
        public const string achievement_thirty_second_samurai = "CgkIpt2t-9MXEAIQBQ"; // <GPGSID>
        public const string leaderboard_level = "CgkIpt2t-9MXEAIQCw"; // <GPGSID>
        public const string achievement_god_tier_gangster = "CgkIpt2t-9MXEAIQCA"; // <GPGSID>
        public const string leaderboard_time = "CgkIpt2t-9MXEAIQDQ"; // <GPGSID>
        public const string achievement_on_the_grind = "CgkIpt2t-9MXEAIQCQ"; // <GPGSID>
        public const string achievement_we_made_it = "CgkIpt2t-9MXEAIQCg"; // <GPGSID>
        public const string leaderboard_experience = "CgkIpt2t-9MXEAIQDA"; // <GPGSID>
        public const string achievement_rookie_runner = "CgkIpt2t-9MXEAIQBg"; // <GPGSID>
        public const string achievement_minute_man = "CgkIpt2t-9MXEAIQBA"; // <GPGSID>

}

